### ISSUE TITLE
BNO08x.hpp: No such file or directory

### ISSUE THREAD

**Issue by MSmithDev** [myles-parfeniuk/esp32_BNO08x#1]
Followed your instructions exactly, using VSCode with ESPIDF extension. 

```
R:/ESPIDF-Projects/testproject/tusb_hid/main/tusb_hid_example_main.cpp:2:10: fatal error: BN008x.hpp: No such file or directory
    2 | #include "BN008x.hpp"
      |          ^~~~~~~~~~~~
compilation terminated.
```

![image_2023-11-13_224701256](https://github.com/myles-parfeniuk/esp32_BNO08x/assets/43940868/cd63397d-f7f2-47a1-9c62-950f99fb10be)
![image_2023-11-13_230044337](https://github.com/myles-parfeniuk/esp32_BNO08x/assets/43940868/fec748b1-4861-48c1-a32b-ea1f7b8b428c)

**Comment by myles-parfeniuk** [comment]
Hello, after reading through your report, I created a fresh project, cloned in the repo, and did not seem to have any issues, but lets see if we can get to the bottom of what's going on here.

Are you able to build esp-idf projects without any external components? 
For example, if you create a project and try to include esp-idf components only, like #include "driver/gpio.h" or #include "esp_log.h", does the project build? Or does it similarly fail to find these?

It is possible that this minor change to my project cmake file made a difference, I forgot to include this part as it's force of habit for me every time I create a new project:

![image](https://github.com/myles-parfeniuk/esp32_BNO08x/assets/138414207/254acfe4-b75f-427f-b88d-56bd3fe6dee2)

Another thing to suggest, this might be obvious, but ensure you run 'idf.py fullclean'/clean the project after you've added new files, before running build. 

Please update me on whether this fixes your issue.

**Comment by MSmithDev** [comment]
I was able to get it to compile changing the CMakeLists file like you suggested. I forgot to bridge two pads on my BNO085 dev board for SPI mode so I can't test it until later. ESPIDF is new to me sorry if it was a simple mistake. My autocomplete doesn't seem to be working any idea on that? I really appreciate the help!

**Comment by myles-parfeniuk** [comment]
No worries, that is actually an oversight on my part. I'll modify the README.md or update the component cmake file so people don't run into the same issue, later tonight or tomorrow. Thank you for bringing my attention to it. 

As for auto-suggest, it has to do with the intellisense not being aware of where the esp-idf components/libraries are stored. You need to modify the properties .json file.

Here is a link to a google doc containing a quick starter guide for esp-idf that I wrote for some friends, it's not professionally put together but it does have a section on fixing auto-suggest (sect. 3.0) and some other stuff you might find useful. 

https://docs.google.com/document/d/1uxoxvMn2i3B611yIz0wAsubbyV9Cy3pB4rNhA0GBcrM/edit?usp=sharing

**Comment by myles-parfeniuk** [comment]
https://docs.google.com/document/d/1uxoxvMn2i3B611yIz0wAsubbyV9Cy3pB4rNhA0GBcrM/edit?usp=sharing
